### PR TITLE
[AMORO-2895] Add more image related properties for the amoro optimizers

### LINKED ISSUE #2895: [Improvement]: Add more image related properties for the amoro optimizers
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

If we want change pullPolicy and imagePullSecrets for spark/flink/kubernetes optimizers,  some configurations wraped for them are needed. But somehow they are not direct for most of us.

### How should we improve?

Add directly these properties in values.yaml for users to use.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by tcodehuber**
## Why are the changes needed?

Close #2895.

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by xleoken — APPROVED** [review]
💯

**Review by czy006 — APPROVED** [review]
LGTM

**Review by baiyangtx — COMMENTED** [review]
That's a good job. Would you please add new properties to docs ?

**Comment by tcodehuber** [comment]
> That's a good job. Would you please add new properties to docs ?

done.

**Comment by zhoujinsong** [comment]
Thanks for the work! @tcodehuber 
Thanks for the review! @baiyangtx @xleoken @czy006

**Pull request merged**
