### PR TITLE
[AMORO-2630] Support choose multi formats when add a new catalog

### LINKED ISSUE #2630: [Subtask]: frontend support choose multi formats when add a new catalog
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### Description

- When adding a new catalog, support for selecting multiple formats.
   -  internal catalog only support mixed-iceberg and iceberg format.
   -  external catalog with hms metastore  supports  mixed-hive/iceberg/mixed-iceberg/paimon
   -  external catalog with other metastore supports  iceberg/mixed-iceberg/paimon 
- When get the detail info of a catalog ,support show the multiple formats

### Parent issue

#1061

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by minteliuwm**
## Why are the changes needed?

Close #2630 .

## Brief change log

- Support choose multi formats when add a new catalog

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [x] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by minteliuwm** [comment]
image

**Comment by Aireed** [comment]
@baiyangtx  do you have time to review again?

**Review by zhangmo8 — APPROVED** [review]
LGTM

**Review by baiyangtx — APPROVED** [review]
LGTM

**Pull request merged**
