### PR TITLE
Move admin username and password to secrets

### PR DESCRIPTION
**Pull request by XBaith**
## Brief change log

- Raising the security level

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by zhoujinsong** [comment]
Thanks for the contribution!

I am curious if the database username and password information is still needed in the configMap as we declare it in the environment.

some codes in amoro-configmap.yaml:
```
database:
        type: {{ .Values.amoroConf.database.type }}
        jdbc-driver-class: {{ .Values.amoroConf.database.driver | quote }}
        url: {{ .Values.amoroConf.database.url }}
        {{- if or (eq .Values.amoroConf.database.type "mysql") (eq .Values.amoroConf.database.type "postgres") }}
        username: {{ .Values.amoroConf.database.username | quote }}
        password: {{ .Values.amoroConf.database.password | quote }}
        {{- end }}
        connection-pool-max-total: 20
        connection-pool-max-idle: 16
        connection-pool-max-wait-millis: 1000
```

**Comment by XBaith** [comment]
> I am curious if the database username and password information is still needed in the configMap as we declare it in the environment.

You are right, we don't need to declare database password in ConfigMap

**Comment by zhoujinsong** [comment]
> You are right, we don't need to declare database password in ConfigMap

We can improve this with another PR.

**Review by zhoujinsong — APPROVED** [review]
LGTM.

**Pull request merged**
