### PR TITLE
[AMORO-3186] Force check git dir when creating release binary

### LINKED ISSUE #3186: [Feature]: Check git dir when creating release binary
### Description

Currently, we don't check where there is a git dir when creating a release binary in `tools/releasing/create_binary_release.sh`,
When reusing this script in-house, we want to check the git dir whenever executing `tools/releaseing/create_binary_release.sh`, and IMHO, this needs to be checked when we do the Apache release also.

### Use case/motivation

_No response_

### Describe the solution

After #3126 has been resolved, we can easily do this check by enabling the profile

### Subtasks

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by klion26**
## Why are the changes needed?

Close #3186.

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

executing `sh releasing/create_binary_release.sh` in `tools` dir

image

## Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by klion26** [comment]
cc @zhoujinsong @zhongqishang

**Review by zhongqishang — APPROVED** [review]
LGTM.

**Comment by zhoujinsong** [comment]
Thanks for the contribution! @klion26

**Comment by klion26** [comment]
@zhoujinsong @zhongqishang thanks for the review and merging!

**Pull request merged**
