### PR TITLE
[AMORO-2888] Can't establish connections when rebooting ams

### LINKED ISSUE #2888: [Bug]: Can't establish connections when rebooting ams
### What happened?

After I updated the amoro image using 0.7-SNAPHOT,  exception logs were met(ams database is mysql8.0):
`amoro-ams Caused by: com.mysql.cj.exceptions.UnableToConnectException: Public Key Retrieval is not allowed`

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### How to reproduce

_No response_

### Relevant log output

```shell
amoro-ams Caused by: com.mysql.cj.exceptions.UnableToConnectException: Public Key Retrieval is not allowed                                                                                                          ││ amoro-ams     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_412]                                                                                                               │
│ amoro-ams     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_412]                                                                                        │
│ amoro-ams     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_412]                                                                                │
│ amoro-ams     at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_412]                                                                                                                     │ | amoro-ams     at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.30.jar:8.0.30]                                                                       │
│ amoro-ams     at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85) ~[mysql-connector-java-8.0.30.jar:8.0.30]                                                                       │
│ amoro-ams     at com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:130) ~[mysql-connector-java-8.0.30.jar:8.0.30]                              │
│ amoro-ams     at com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:49) ~[mysql-connector-java-8.0.30.jar:8.0.30]                               │
│ amoro-ams     at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:447) ~[mysql-connector-java-8.0.30.jar:8.0.30]                  │
│ amoro-ams     at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:212) ~[mysql-connector-java-8.0.30.jar:8.0.30]                                                      │
│ amoro-ams     at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1433) ~[mysql-connector-java-8.0.30.jar:8.0.30]                                                                                 │
│ amoro-ams     at com.mysql.cj.NativeSession.connect(NativeSession.java:133) ~[mysql-connector-java-8.0.30.jar:8.0.30]                                                                                               │
│ amoro-ams     at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:842) ~[mysql-connector-java-8.0.30.jar:8.0.30]                                                                             │
│ amoro-ams     at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823) ~[mysql-connector-java-8.0.30.jar:8.0.30]                                                                                    │
│ amoro-ams     at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448) ~[mysql-connector-java-8.0.30.jar:8.0.30]                                                                                         │
│ amoro-ams     at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241) ~[mysql-connector-java-8.0.30.jar:8.0.30]                                                                                    │
│ amoro-ams     at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.30.jar:8.0.30]                                                                            │
│ amoro-ams     at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:52) ~[commons-dbcp2-2.9.0.jar:2.9.0]                                                                │
│ amoro-ams     at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:374) ~[commons-dbcp2-2.9.0.jar:2.9.0]                                                                 │
│ amoro-ams     at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:106) ~[commons-dbcp2-2.9.0.jar:2.9.0]                                                                      │
│ amoro-ams     at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:649) ~[commons-dbcp2-2.9.0.jar:2.9.0]                                                                │
│ amoro-ams     at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:531) ~[commons-dbcp2-2.9.0.jar:2.9.0]                                                                               │
│ amoro-ams     at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:731) ~[commons-dbcp2-2.9.0.jar:2.9.0]                                                                                  │
│ amoro-ams     at org.apache.ibatis.transaction.jdbc.JdbcTransaction.openConnection(JdbcTransaction.java:145) ~[mybatis-3.5.15.jar:3.5.15]                                                                           │
│ amoro-ams     at org.apache.ibatis.transaction.jdbc.JdbcTransaction.getConnection(JdbcTransaction.java:67) ~[mybatis-3.5.15.jar:3.5.15]                                                                             │
│ amoro-ams     at org.apache.ibatis.session.defaults.DefaultSqlSession.getConnection(DefaultSqlSession.java:297) ~[mybatis-3.5.15.jar:3.5.15]                                                                        │
│ amoro-ams     at org.apache.amoro.server.persistence.SqlSessionFactoryProvider.createTablesIfNeed(SqlSessionFactoryProvider.java:130) ~[amoro-ams-server-0.7-SNAPSHOT.jar:?]                                        │
│ amoro-ams     ... 6 more
```

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tcodehuber**
## Why are the changes needed?

Close #2888.

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by zhoujinsong** [comment]
@tcodehuber Thanks for the contribution!

But I am not sure if `allowPublicKeyRetrieval=true` is a common property to all MySQL versions.

**Comment by tcodehuber** [comment]
> allowPublicKeyRetrieval=true

Although it's imported by mysql8, adding it in the con url will not affect other editions of mysql. It will be ignored if connecting to the mysql below version 8, which will not take side effort.

**Review by zhoujinsong — APPROVED** [review]
LGTM.

**Comment by zhoujinsong** [comment]
> Although it's imported by mysql8, adding it in the con url will not affect other editions of mysql. It will be ignored if connecting to the mysql below version 8, which will not take side effort. I have tested that in my own env.

Thanks for the information.

**Pull request merged**
