### PR TITLE
[AMORO-2731]: remove unuse import

### LINKED ISSUE #2731: [Subtask]: antd-vue 4.x version overall theme style adaptation existing version
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### Description

antd-vue 4.x version overall theme style adaptation existing version

### Parent issue

#2728 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhangmo8**
## Why are the changes needed?

Close #2731, remove unused import

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by zhangmo8** [comment]
#2731

**Comment by zhoujinsong** [comment]
Can you help to review it? @minteliuwm

**Review by minteliuwm — APPROVED** [review]
LGTM

**Review by zhoujinsong — APPROVED** [review]
Thanks for the work @zhangmo8 
Thanks for the review @minteliuwm

**Pull request merged**
