### PR TITLE
[AMORO-2797] Improve ams metrics module naming

### LINKED ISSUE #2797: [Improvement] Improve ams metrics module naming
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Refered to Iceberg, Paimon, Hudi and Flink.

Only Flink has a module named as flink-metrics which has quite similar logic to Amoro:
image

When it comes to Paimon, Hudi and Iceberg, they all have packages named as metrics.

I think metric-reporter is too granular and metrics should be reasonable for both extensibility and readibility.

### How should we improve?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by majin1102**
## Why are the changes needed?

Close #2797.

## Brief change log

- Improve metrics module naming and fix a warning

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by zhongqishang — CHANGES_REQUESTED** [review]
Thanks for your contribution, `bin.xml` has not been modified, causing ci to fail.

https://github.com/apache/amoro/blob/970127ef9050c506b1b147347dee943622afea0c/amoro-ams/dist/src/main/assemblies/bin.xml?plain=1#L48-L50

**Comment by majin1102** [comment]
> Thanks for your contribution, `bin.xml` has not been modified, causing ci to fail.
> 
> https://github.com/apache/amoro/blob/970127ef9050c506b1b147347dee943622afea0c/amoro-ams/dist/src/main/assemblies/bin.xml?plain=1#L48-L50

Thanks for pointing that out.
I will fix it soon

**Review by zhongqishang — APPROVED** [review]
LGTM.

**Review by baiyangtx — APPROVED** [review]
LGTM

**Review by czy006 — APPROVED** [review]
LGTM

**Pull request merged**
