### PR TITLE
[Doc]Fix typo in managing-optimizers.md

### PR DESCRIPTION
**Pull request by xieyi888**
## Why are the changes needed?

Fix typo in managing-optimizers.md

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by huyuanfeng2018** [comment]
@xieyi888 
Thank you very much for your contribution, can you submit this PR to this project?
https://github.com/apache/amoro-site/blob/master/amoro-docs/content/admin-guides/managing-optimizers.md

**Review by tcodehuber — APPROVED** [review]
LGTM

**Comment by huyuanfeng2018** [comment]
> @xieyi888 
> Thank you very much for your contribution, can you submit this PR to this project?
> https://github.com/apache/amoro-site/blob/master/amoro-docs/content/admin-guides/managing-optimizers.md

I was wrong. doc will synchronize the website

**Review by huyuanfeng2018 — APPROVED** [review]
LGTM.

**Pull request merged**
