### PR TITLE
[AMORO-2733] Added db_type configuration check. database.type is mand…

### LINKED ISSUE #2733: [Bug]: Lack of database.type mandatory check in config, leading to NPE in existing MySQL config check
### What happened?

Given malformatted config.yaml or missing `database.type`, then the existing mysql config check segment would throw NPE. The exception message is misleading.

### Affects Versions

master/0.6.1

### What engines are you seeing the problem on?

Core, Flink, Spark

### How to reproduce

Provide a config.yaml without database.type option. Then start ams.

### Relevant log output

```shell
2024-04-10 17:44:14,579 ERROR [main] [com.netease.arctic.server.ArcticServiceContainer] [] - AMS encountered an unknown exception, will exist
java.lang.NullPointerException: null
        at com.netease.arctic.server.ArcticServiceContainer$ConfigurationHelper.validateConfig(ArcticServiceContainer.java:415) ~[amoro-ams-server-0.6.0.jar:?]
        at com.netease.arctic.server.ArcticServiceContainer$ConfigurationHelper.initServiceConfig(ArcticServiceContainer.java:392) ~[amoro-ams-server-0.6.0.jar:?]
        at com.netease.arctic.server.ArcticServiceContainer$ConfigurationHelper.init(ArcticServiceContainer.java:375) ~[amoro-ams-server-0.6.0.jar:?]
        at com.netease.arctic.server.ArcticServiceContainer.initConfig(ArcticServiceContainer.java:189) ~[amoro-ams-server-0.6.0.jar:?]
        at com.netease.arctic.server.ArcticServiceContainer.<init>(ArcticServiceContainer.java:99) ~[amoro-ams-server-0.6.0.jar:?]
        at com.netease.arctic.server.ArcticServiceContainer.main(ArcticServiceContainer.java:105) [amoro-ams-server-0.6.0.jar:?]
2024-04-10 18:44:32,300 ERROR [JettyServerThreadPool-153] [com.netease.arctic.server.dashboard.DashboardServer] [] - Failed to handle request
java.lang.IllegalStateException: Cannot find memory in properties
        at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkState(Preconditions.java:590) ~[iceberg-bundled-guava-1.3.0.jar:?]
        at com.netease.arctic.ams.api.resource.Resource.getRequiredProperty(Resource.java:70) ~[amoro-ams-api-0.6.0.jar:?]
        at com.netease.arctic.server.manager.LocalOptimizerContainer.buildOptimizerStartupArgsString(LocalOptimizerContainer.java:55) ~[amoro-ams-server-0.6.0.jar:?]
        at com.netease.arctic.server.manager.LocalOptimizerContainer.doScaleOut(LocalOptimizerContainer.java:37) ~[amoro-ams-server-0.6.0.jar:?]
        at com.netease.arctic.server.manager.AbstractResourceContainer.requestResource(AbstractResourceContainer.java:43) ~[amoro-ams-server-0.6.0.jar:?]
        at com.netease.arctic.server.dashboard.controller.OptimizerController.scaleOutOptimizer(OptimizerController.java:206) ~[amoro-ams-server-0.6.0.jar:?]
        at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:20) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServlet.addHandler$lambda-0(JavalinServlet.kt:96) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:98) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981) ~[?:1.8.0_121]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124) ~[?:1.8.0_121]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-10$lambda-9(JavalinServletHandler.kt:112) ~[javalin-4.6.1.jar:4.6.1]
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_121]
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614) ~[?:1.8.0_121]
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983) ~[?:1.8.0_121]
        at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:112) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981) ~[?:1.8.0_121]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124) ~[?:1.8.0_121]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-10$lambda-9(JavalinServletHandler.kt:112) ~[javalin-4.6.1.jar:4.6.1]
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_121]
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614) ~[?:1.8.0_121]
```

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by paul8263**
…atory

## Why are the changes needed?

Close #2733.

## Brief change log

- ams/server/src/main/java/com/netease/arctic/server/ArcticServiceContainer.java

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [x] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? no
- If yes, how is the feature documented? not documented

### CODE REVIEW

**Review by zhoujinsong — APPROVED** [review]
LGTM.

Thanks for the contribution! @paul8263

**Comment by paul8263** [comment]
Applied another minor change and fixed the checkstyle error. Pls review it again. Thanks.

**Comment by zhongqishang** [comment]
```
      validateConfig(expandedConfigurationMap);
      serviceConfig = Configurations.fromObjectMap(expandedConfigurationMap);
```

@paul8263 @zhoujinsong 

Would it be better if we adjusted the order of these two lines? 
- `SqlSessionFactoryProvider.getInstance().init(serviceConfig)` will can use some default values, this will be reduce error. 
- We can use `Configurations#getString()` to get value.
WDYT?

**Comment by paul8263** [comment]
> ```
>       validateConfig(expandedConfigurationMap);
>       serviceConfig = Configurations.fromObjectMap(expandedConfigurationMap);
> ```
> 
> @paul8263 @zhoujinsong
> 
> Would it be better if we adjusted the order of these two lines?
> 
> * `SqlSessionFactoryProvider.getInstance().init(serviceConfig)` will can use some default values, this will be reduce error.
> * We can use `Configurations#getString()` to get value.
>   WDYT?

Agreed with swapping the two lines of codes. We can first convert the Map to Configurations and then check the validity of it.

Another benefit of converting it to Configurations first is the default value could be resolved by the config option definition.

If applicable I would like to do this job.

**Review by zhongqishang — APPROVED** [review]
Thanks for your contribution, LGTM.

**Comment by zhongqishang** [comment]
@paul8263 Merged first and the improvement can be made in the new PR .

**Comment by paul8263** [comment]
Hi @zhongqishang ,

Thanks. I'll file another issue about the optimization.

**Pull request merged**
