### PR TITLE
[AMORO-3143] Supports executing the spotless apply command on a single module

### LINKED ISSUE #3143: [Bug]: Executing spotless apply of a module alone will report an error that the file cannot be found.
### What happened?

As title

### Affects Versions

master

### What table formats are you seeing the problem on?

_No response_

### What engines are you seeing the problem on?

_No response_

### How to reproduce

If you execute `spotless: apply` on a module alone, an error will be reported:

Could not find resource 'tools/maven/scalafmt.conf'.

### Relevant log output

_No response_

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by engraving-knife**
## Why are the changes needed?

Close #3143.

## Brief change log

- Modify the configuration file address of the spotless plug-in

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by zhongqishang** [comment]
@engraving-knife Thanks for your contribution.

IMO, maybe use `maven.multiModuleProjectDirectory` will be better, like 

```
<file>${maven.multiModuleProjectDirectory}/tools/maven/scalafmt.conf</file>
```

FYI, In Maven 4.0, more options are provided. https://issues.apache.org/jira/browse/MNG-7038

**Comment by engraving-knife** [comment]
@zhongqishang Thanks for your suggestion. I tried the `multiModuleProjectDirectory` attribute but it doesn't seem to work.

In addition, the official provides new properties to get the root directory of multi-module projects, but I think we should not use the properties of unreleased maven versions.

image

**Comment by zhongqishang** [comment]
> @zhongqishang Thanks for your suggestion. I tried the `multiModuleProjectDirectory` attribute but it doesn't seem to work.

Sorry for the missing information, also need to configure the `maven.multiModuleProjectDirectory` in VM options.

image

**Review by czy006 — COMMENTED** [review]
If we have appropriate doc describing the best practices. by the way, can this feature generate a binary installation package for a specific table's schema variation?

**Pull request closed without merging**
