### PR TITLE
[AMORO-2813] Improve the version info about the project

### LINKED ISSUE #2813: [Improvement]: Improve the version info about the project
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, the version info displayed at the topbar shows the version and the build time(such as`Version: 0.7.0-SNAPSHOTCommit Time: 2024-04-18T16:12:39+0800`) this is enough for the release version, but it may not enough when developing.

### How should we improve?

we can include the abbrev property in the version info such as (`Version: 0.7.0-SNAPSHOT(1fa68ab) Commit Time: 2024-04-18T16:12:39+0800`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by klion26**
## Why are the changes needed?

Close #2813 

 Before this commit, it would only show the version of the project at the topbar,   but this may not be enough for some cases, in this commit we enhanced the version info by including the abbrev.

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by klion26** [comment]
cc @zhoujinsong

**Review by zhongqishang — COMMENTED** [review]
It's great, if change the folder name of `git.properties` from `arctic` to `amoro` will be better. Can you fix it together?

**Comment by klion26** [comment]
@zhongqishang good catch-up, fixed it.

After checking the jar file `amoro-ams-server-0.7-SNAPSHOT.jar`, it looks fine. 
image

Didn't run end-to-end test locally, because there is something wrong with the login page, didn't figure the reason currently.

image

**Comment by zhongqishang** [comment]
image

I verified this after revert #2773.

**Review by zhongqishang — APPROVED** [review]
LGTM.

**Review by XBaith — APPROVED** [review]
Thanks for your contribute. LGTM

**Comment by klion26** [comment]
@zhongqishang @XBaith thanks for the review and merging!

**Pull request merged**
