### PR TITLE
[AMORO-3228] Rewrite pos delete files not written by optimizing process

### LINKED ISSUE #3228: [Bug]: Iceberg table ran repeated minor optimizing
### What happened?

When Spark deletes data from the Iceberg table using the merge-on-read mode, Iceberg may repeatedly perform minor optimizing.

### Affects Versions

master

### What table formats are you seeing the problem on?

Iceberg

### What engines are you seeing the problem on?

AMS

### How to reproduce

- Create an iceberg table
- Insert some data
- Delete some data with merge-on-read mode several times 

### Relevant log output

_No response_

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by zhoujinsong**
## Why are the changes needed?

Close #3228.

## Brief change log

- Rewrite all pos delete files not written by optimizing process

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by zhoujinsong** [comment]
The root cause of #3228 is that the minor optimizing process will be triggered if an insert file has 2 or more pos delete files.
But the pos delete file cannot be removed if not all insert files across with this delete file are optimized in this process.

So we should rewrite all pos delete files not written by optimizing process because they are written by other engines and may be across multiple insert files.

**Review by majin1102 — APPROVED** [review]
LGTM

**Review by zhongqishang — APPROVED** [review]
LGTM.

**Comment by zhoujinsong** [comment]
Thanks for the review, @majin1102 @zhongqishang

**Pull request merged**
