### PR TITLE
[AMORO-2938] Add common dependency chart

### LINKED ISSUE #2938: [Improvement]: Add common dependency chart
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Due to the network issue, it's very hard for us to pull the common dependency from `registry-1.docker.io`. We can add the dependency to the project directly.

### How should we improve?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xleoken**
## Why are the changes needed?

Close #2938.

## Brief change log

Due to the network issue, it's very very hard for us to pull the common dependency from `registry-1.docker.io`. We can add the dependency to the project directly.

```
# helm dependency build
Error: no repository definition for oci://registry-1.docker.io/bitnamicharts. Please add the missing repos via 'helm repo add'

# ping registry-1.docker.io
PING registry-1.docker.io (54.196.99.49) 56(84) bytes of data.
```

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by czy006** [comment]
We cannot review the contents of the compressed package, which may be risky. Can we specify the pull this common method through http get it ?

**Comment by xleoken** [comment]
> We cannot review the contents of the compressed package, which may be risky. Can we specify the pull this common method through http get it ?

emm, it seems no other ways. I used gcp to download the dependency.
17abdb54e2c452564174295c9aa70a5

**Comment by baiyangtx** [comment]
It's not a good idea to add a `tgz` file to git repo. 

Maybe you can build the amoro helm package in an environment where the network allows it and then distribute it to the environment where it needs to be deployed

**Comment by baiyangtx** [comment]
Or Amoro can maintain built helm charts. 
Currently, the Amoro project provides packaged charts in gh-pages, but this branch is not maintained. 
Perhaps you can add a workflow to maintain this distribution

**Comment by xleoken** [comment]
> It's not a good idea to add a `tgz` file to git repo.
> 
> Maybe you can build the amoro helm package in an environment where the network allows it and then distribute it to the environment where it needs to be deployed

ok, let me think again.

**Comment by xleoken** [comment]
@baiyangtx @czy006 

I copied some templates files from `bitnami/charts` repository. 

like doris does.
https://github.com/apache/doris/blob/a831aabac493195d0048eaf8c0b21c77bb8bd674/be/src/vec/functions/function_quantile_state.cpp#L17

**Comment by daragu** [comment]
This problem has been bothering me for a long time, nice to see that this issue is resolving.

**Comment by kristgpt** [comment]
It's also difficult for me to download the common dependency.

**Review by baiyangtx — COMMENTED** [review]
Is it possible to put these files into a separate directory?

**Comment by xleoken** [comment]
> Is it possible to put these files into a separate directory?

Good idea, updated.

image

**Review by baiyangtx — APPROVED** [review]
LGTM, thanks for your contributions

**Comment by zhoujinsong** [comment]
Thanks for the work! @xleoken 
Thanks for the review! @baiyangtx

**Pull request merged**
