### PR TITLE
[hotfix]Fix the incorrent paramater transmission of PageNum and PageSize

### PR DESCRIPTION
**Pull request by zhangwl9**
## Why are the changes needed?

Close #xxx.

## Brief change log

We need to to transmit parameters of pageNum and pageSize in 'PageHelper#startPage' and the TableMetaMapper#selectTableRuntimesForOptimizerGroup,OptimizingMapper#selectOptimizingProcesses.

We correct the inconsistent problem.

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by zhangwl9** [comment]
@klion26  @czy006 Could you please take a look at this when you're free, thanks

**Comment by klion26** [comment]
@zhangwl9 thanks for the contribution, the change here LGTM.

As there was some ut want to cover the logic, so could you please help to check
1. if the logic here in the master is right or not(if the code logic in the master branch can give the right result, maybe it is because the parameter in `PageHelper.startPage(pageNumber, limit, true)` -- line 517 has a higher priority than the parameter in the mapper)
2. if the logic here in the master is wrong, could you please please add more ut to cover the logic

**Review by baiyangtx — COMMENTED** [review]
After introducing github.PageHelper, do we still need to pass the pageNumber and limit parameters to the mapper? 

It seems that these two parameters are not required in the process of constructing SQL.

**Comment by zhangwl9** [comment]
> @zhangwl9 thanks for the contribution, the change here LGTM.
> 
> As there was some ut want to cover the logic, so could you please help to check
> 
> 1. if the logic here in the master is right or not(if the code logic in the master branch can give the right result, maybe it is because the parameter in `PageHelper.startPage(pageNumber, limit, true)` -- line 517 has a higher priority than the parameter in the mapper)
> 2. if the logic here in the master is wrong, could you please help to enhance the exist ut to cover the logic

Thank you very much for your advice. I have tested and found the following:

1) The parameter (pageNumber,limit) in PageHelper.startPage(pageNumber, limit, true) -- line 517 has a higher priority than the parameter(pageNum, pageSize) in the mapper, as shown in figure 
image


2) When building the mapper's SQL statement, if the parameters pageNum and pageSize are removed, amoro displays normally, as shown in the figure.
image

Therefore, pageNum and pageSize are not needed during SQL construction. I have already fixed it.

 3) Two unit tests involving mappers: TestIcebergServerTableDescriptor#testOptimizingPorcess and TestDefaultOptimizingService#testGetRuntimes can both cover the results of PageHelper and PageInfo, therefore, no new unit tests need to be added.

**Comment by zhangwl9** [comment]
> After introducing github.PageHelper, do we still need to pass the pageNumber and limit parameters to the mapper?
> 
> It seems that these two parameters are not required in the process of constructing SQL.
@baiyangtx  Thank you very much for your advice. You are right. I have fix it.

**Review by klion26 — APPROVED** [review]
Thanks for the fix, LGTM

**Comment by klion26** [comment]
@zhangwl9 Seems there are some tests failed, could you please help to check it, thanks.

**Review by czy006 — APPROVED** [review]
LGTM

**Pull request merged**
