### PR TITLE
[MINOR] Put mvn config files together

### PR DESCRIPTION
**Pull request by daragu**
## Why are the changes needed?

Minor.

## Brief change log

Put mvn config files together.

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by xleoken** [comment]
LGTM

**Review by zhoujinsong — COMMENTED** [review]
@daragu Thanks for the contribution!

It seems that the files were not moved to the `tools/maven` folder. You may want to have a check.

**Comment by daragu** [comment]
> @daragu Thanks for the contribution!
> 
> It seems that the files were not moved to the `tools/maven` folder. You may want to have a check.

Thanks.

**Review by zhoujinsong — APPROVED** [review]
LGTM.

**Pull request merged**
