### PR TITLE
[AMORO-2802] Change the folder name of optimizer module

### LINKED ISSUE #2802: [Improvement]: Add prefix `amoro-` for optimizer module and keep same with folder
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

image

Rename module to prefix with `amoro-` and keep the same name with folder.

### How should we improve?

Rename to

- amoro-optimizer-common
- amoro-optimizer-flink
- amoro-optimizer-spark
- amoro-optimizer-standalone

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhongqishang**
## Why are the changes needed?

Close #2802 .

## Brief change log

- Add prefix `amoro`
- Keep the same with module and folder name

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / **no**)
- If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by xleoken — APPROVED** [review]

**Comment by xleoken** [comment]
lgtm

**Comment by zhoujinsong** [comment]
Hi,

We used to say Flink optimizer/Spark optimizer. So do you think `amoro-flink-optimizer`/`amoro-spark-optimizer` is a proper name for both the artifact id and the folder name?

**Comment by xleoken** [comment]
> `amoro-flink-optimizer`/`amoro-spark-optimizer`

`amoro-flink-optimizer`/`amoro-spark-optimizer` is better.

**Comment by zhongqishang** [comment]
> Hi,
> 
> We used to say Flink optimizer/Spark optimizer. So do you think `amoro-flink-optimizer`/`amoro-spark-optimizer` is a proper name for both the artifact id and the folder name?

@zhoujinsong @xleoken 

Yes, we used to say Flink/Spark optimizer, in order to maintain the unity of the module format, I looked at the flink connector. 
Like the structure of flink connector, the module name does not affect us calling it flink kafka connector[1].

[1] : https://github.com/apache/flink-connector-kafka

**Comment by xleoken** [comment]
hi @zhongqishang @zhoujinsong 

We can keep the style as `amoro-mixed-format` module, so `amoro-optimizer-flink` and `amoro-optimizer-spark` is ok.

amoro-mixed-format
- amoro-mixed-format-flink
- amoro-mixed-format-hive
- amoro-mixed-format-spark
- amoro-mixed-format-trino

**Review by zhoujinsong — APPROVED** [review]
Make sense to me.

**Pull request merged**
