### PR TITLE
[Hotfix] Fix the value of authType is always null

### PR DESCRIPTION
**Pull request by xleoken**
## Why are the changes needed?

As title.

## Brief change log

We should use `CatalogMeta#getAuthConfigs` instead of `CatalogMeta#getCatalogProperties`.
```
CatalogMeta(catalogName:test, catalogType:custom, storageConfigs:{storage.type=S3}, authConfigs:{auth.type=ak/sk}, catalogProperties:{s3.access-key-id=c, s3.secret-access-key=b, table.self-optimizing.group=test, s3.endpoint=a, catalog-impl=org.apache.iceberg.rest.ABCD, table-formats=ICEBERG, client.region=a})
```

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by zhoujinsong — APPROVED** [review]
LGTM.

Thanks for the work! @xleoken

**Comment by zhoujinsong** [comment]
Hi, can you help me confirm the impact of this issue? This will determine whether the fix needs to be included in version 0.7.0.

**Comment by xleoken** [comment]
> Hi, can you help me confirm the impact of this issue? This will determine whether the fix needs to be included in version 0.7.0.

ok, let's wait the ci first.

**Comment by xleoken** [comment]
hi @zhoujinsong, there is the same logic here, we just need to keep one of them, what do you think?

image

**Comment by xleoken** [comment]
Thanks for reviewing @zhoujinsong. Close this issue due to https://github.com/apache/amoro/pull/2972

**Pull request closed without merging**
