### PR TITLE
[Improvement] set engines to prompt the lowest version of node and format code

### PR DESCRIPTION
**Pull request by chouchouji**
## Why are the changes needed?

Close #xxx.

## Brief change log

image

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by tcodehuber — APPROVED** [review]
LGTM

**Review by songjianet — APPROVED** [review]

**Comment by zhoujinsong** [comment]
Hi,

Make we should change the required version here:
https://github.com/apache/amoro/tree/master/amoro-ams/amoro-ams-dashboard#requirements

Besides, upgrade the version here:
https://github.com/apache/amoro/blob/master/amoro-ams/amoro-ams-dashboard/pom.xml#L35

**Review by zhangmo8 — APPROVED** [review]
LGTM

**Comment by chouchouji** [comment]
> Hi,
> 
> Mabe we should change the required version here: https://github.com/apache/amoro/tree/master/amoro-ams/amoro-ams-dashboard#requirements
> 
> Besides, upgrade the version here: https://github.com/apache/amoro/blob/master/amoro-ams/amoro-ams-dashboard/pom.xml#L35

Done, please review again.

**Review by zhoujinsong — APPROVED** [review]
LGTM.

Thanks for the contribution!

**Pull request merged**
