### PR TITLE
[Improvement]: Add missing optimizingStatus key and format code

### PR DESCRIPTION
**Pull request by chouchouji**
## Why are the changes needed?

ef5cda8c-d40d-4683-94b5-e8bed6f1b5cd

**I add optimizingStatus key for IBaseDetailInfo interface. It fixed successfully. Please check screenshot below.** 

image

### CODE REVIEW

**Review by czy006 — APPROVED** [review]
LGTM

**Comment by chouchouji** [comment]
> LGTM

Thanks for your review!

**Comment by zhoujinsong** [comment]
Dose this PR solve any issue or bug?

Sorry for my lack of background in this PR.

**Comment by chouchouji** [comment]
> Dose this PR solve any issue or bug?
> 
> Sorry for my lack of background in this PR.

It is only a type error in dashboard. Sorry, I don't open one issue to describe it. More details please check this pr summary.

**Comment by zhoujinsong** [comment]
Thanks for the contribution! @chouchouji

**Comment by klion26** [comment]
Hi @chouchouji dose this problem exist in release-0.7?

**Comment by chouchouji** [comment]
> Hi @chouchouji dose this problem exist in release-0.7?

The pr was closed in recent days. The last version was published in Aug 2. So I guess it is not in release-0.7. @zhoujinsong Can you answer this question? Tnank you!

**Comment by zhoujinsong** [comment]
Yes, this PR should be cherrypicked to branch 0.7.x.

**Pull request merged**
