### PR TITLE
[hotfix] Replace OptimizingProcess#Status with ProcessStatus.

### PR DESCRIPTION
**Pull request by zhangwl9**
## Why are the changes needed?

Replace OptimizingProcess#Status with ProcessStatus.
## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x]  Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by klion26** [comment]
thanks for your contribution, LGTM, @majin1102 @czy006 could you please take a look at this when you're free, thanks

**Review by czy006 — APPROVED** [review]
LGTM. cc @majin1102

**Review by baiyangtx — APPROVED** [review]
LGTM

**Comment by zhoujinsong** [comment]
Thanks for the contribution! @zhangwl9

**Pull request merged**
