### PR TITLE
[AMORO-2768] Change the folder name of the module to match the artifactId

### LINKED ISSUE #2768: [Improvement]: Change the folder name of the module to match the artifactId
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Change the folder name of the module to match the artifactId

### How should we improve?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xleoken**
## Why are the changes needed?

Change the folder name of the module to match the artifactId

Close #2768.

## Brief change log
Change the folder name of the module to match the artifactId.

image

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by xleoken** [comment]
cc @zhongqishang

**Comment by xleoken** [comment]
cc @zhongqishang @zhoujinsong

**Review by zhoujinsong — APPROVED** [review]
@xleoken Thanks a lot for the work!

Keeping the folder name the same with the artifact id is a good improvement.

**Comment by zhongqishang** [comment]
@xleoken Thanks for your contribution. 
With this change, can you update the `Modules` and `Building` parts in the [README.md](https://github.com/apache/amoro/blob/master/README.md)?

**Comment by zhongqishang** [comment]
And `labeler.yml`.

**Comment by zhongqishang** [comment]
link #2780 #2781

**Pull request merged**
