### PR TITLE
[AMORO-2407] Fix access data file from dashboard of non-partitioned table

### LINKED ISSUE #2407: [Bug]: TableController set partition to string value “null” when getting file list for a non-partitioned table
### What happened?

Error occurs when access to table files of a non-partitioned table

image

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### How to reproduce

- create an internal catalog
- create iceberg table without partition filed
- access data file from dashboard

### Relevant log output

```shell
java.lang.IllegalArgumentException: Invalid partition data, too many fields (expecting 0): null
        at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkArgument(Preconditions.java:326) ~[iceberg-bundled-guava-1.3.0.jar:?]
        at com.netease.arctic.utils.ArcticDataFiles.data(ArcticDataFiles.java:89) ~[amoro-core-0.7.0-SNAPSHOT.jar:?]
        at com.netease.arctic.server.dashboard.MixedAndIcebergTableDescriptor.collectFileInfo(MixedAndIcebergTableDescriptor.java:503) ~[amoro-ams-server-0.7.0-SNAPSHOT.jar:?]
        at com.netease.arctic.server.dashboard.MixedAndIcebergTableDescriptor.getTableFilesInternal(MixedAndIcebergTableDescriptor.java:491) ~[amoro-ams-server-0.7.0-SNAPSHOT.jar:?]
        at com.netease.arctic.server.dashboard.MixedAndIcebergTableDescriptor.getTableFiles(MixedAndIcebergTableDescriptor.java:396) ~[amoro-ams-server-0.7.0-SNAPSHOT.jar:?]
        at com.netease.arctic.server.dashboard.ServerTableDescriptor.getTableFile(ServerTableDescriptor.java:110) ~[amoro-ams-server-0.7.0-SNAPSHOT.jar:?]
        at com.netease.arctic.server.dashboard.controller.TableController.getPartitionFileListInfo(TableController.java:461) ~[amoro-ams-server-0.7.0-SNAPSHOT.jar:?]
```

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by liaoyt**
## Why are the changes needed?

Close #2407

## Brief change log

- convert string value "null" to null

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? no

### CODE REVIEW

**Review by zhoujinsong — APPROVED** [review]
LGTM.

Thanks a lot for your contribution!

**Comment by zhoujinsong** [comment]
@liaoyt 

After I review the code of `MixedAndIcebergTableDescriptor#collectFileInfo`, I found a possibly better way to fix the issue.
We can change the conditions here(https://github.com/NetEase/amoro/blob/master/ams/server/src/main/java/com/netease/arctic/server/dashboard/MixedAndIcebergTableDescriptor.java#L502) like this:
```
if (table.spec().isPartitioned() && partition != null && specId != null) {
  GenericRecord partitionData = ArcticDataFiles.data(specs.get(specId), partition);
  manifestReader.inPartitions(specs.get(specId), partitionData);
}
```

Then we won't confuse non-partitioned tables with partitioned values that are null.
HDYT? @liaoyt

**Comment by wangtaohz** [comment]
I'm a little worried if Paimon has the same issue, cc @shidayang.

**Comment by liaoyt** [comment]
> After I review the code of `MixedAndIcebergTableDescriptor#collectFileInfo`, I found a possibly better way to fix the issue. We can change the conditions here(https://github.com/NetEase/amoro/blob/master/ams/server/src/main/java/com/netease/arctic/server/dashboard/MixedAndIcebergTableDescriptor.java#L502) like this:
> 
> ```
> if (table.spec().isPartitioned() && partition != null && specId != null) {
>   GenericRecord partitionData = ArcticDataFiles.data(specs.get(specId), partition);
>   manifestReader.inPartitions(specs.get(specId), partitionData);
> }
> ```
> 
> Then we won't confuse non-partitioned tables with partitioned values that are null. HDYT? @liaoyt

it looks more reasonable

**Review by wangtaohz — APPROVED** [review]
LGTM

**Review by shidayang — APPROVED** [review]
+1

**Pull request merged**
