### PR TITLE
[AMORO-3027]: Support Paimon Consumer Info in Ams

### LINKED ISSUE #3027: [Feature]: Support Paimon Consumer Info in Ams
### Description

Users want to view the current consumption status of the [Paimon table seems kafka](https://paimon.apache.org/docs/0.8/append-table/append-queue/#definition) on the AMS interface so as to trace the current consumption progress and status of the Paimon table.We need to provide a set of interfaces for query.

### Use case/motivation

Add [Paimon Consumer info](https://paimon.apache.org/docs/master/maintenance/system-tables/#consumers-table) in AMS to Rest Api query

### Describe the solution

- Add Consumer Rest Api 
- implemente Paimon ConsumerManager to get ConsumerInfo

### Subtasks

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by czy006**
## Why are the changes needed?

Close #3027.

## Brief change log

- Add getTableConsumerInfos interface and impl in FormatTableDescriptor
- Add getTableConsumerInfos in AMS Rest Api

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible
- [x] Add screenshots for manual tests if appropriate
- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes)
- If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Comment by czy006** [comment]
image

**Comment by czy006** [comment]
image

**Comment by czy006** [comment]
```
CREATE TABLE print_paimon_table (
  debezium_json STRING,
  database_name STRING,
  table_name STRING,
  partition_key STRING,
  partition_value STRING,
  kafka_offset int,
  kafka_partition bigint,
  dt STRING
) WITH ('connector' = 'blackhole');
CREATE CATALOG tb_catalog WITH (
  'type' = 'paimon',
  'warehouse' = 'hdfs:///flink/warehouse'
);
use CATALOG tb_catalog;
INSERT INTO
  default_catalog.default_database.print_paimon_table
select
  debezium_json,
  database_name,
  table_name,
  partition_key,
  partition_value,
  kafka_offset,
  kafka_partition,
  dt
from
  tb_cdc_db_torrent_table
  /*+ OPTIONS('scan.snapshot-id' = '111','consumer-id' = 'test2') */;
```
image

image

**Review by baiyangtx — APPROVED** [review]
LGTM

**Pull request merged**
