### PR TITLE
[AMORO-2669]: use the faker plugin replace mock plugin

### LINKED ISSUE #2669: [Feature]: Use fakerjs to replace vite-plugin-mock
### Description

Use fakerjs to replace vite-plugin-mock

because of [link](https://github.com/vbenjs/vite-plugin-mock/issues/127)

### Use case/motivation

_No response_

### Describe the solution

_No response_

### Subtasks

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhangmo8**
## Why are the changes needed?

mock plugin prod mode hard to use

Close #2669 .

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by zhangmo8** [comment]
@tcodehuber Sorry to bother you at this time, could you please take the time to review it?

**Review by tcodehuber — APPROVED** [review]
LGTM, thanks for your contribution.

**Review by baiyangtx — COMMENTED** [review]
The frontend part should be recompiled after modifying the dashboard code

**Review by minteliuwm — APPROVED** [review]
LGTM

**Comment by zhangmo8** [comment]
> The frontend part should be recompiled after modifying the dashboard code

Hi @baiyangtx . Now the front end can automatically submit the built files through the Maven plugin.
It's [Here](https://github.com/apache/incubator-amoro/pull/2670)

**Pull request merged**
