### PR TITLE
[AMORO-3317]: Move optimizing planer and scan to iceberg/mixed-format module

### LINKED ISSUE #3317: [Subtask]:  Move optimizing planer and scan to iceberg/mixed-format module
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### Description

Make Optimizer is able to access the OptimizingPlaner logic.

### Parent issue

#3315 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by baiyangtx**
## Why are the changes needed?

close #3317

Currently, the Optimizing Plan has become a bottleneck of AMS. A feasible solution is to delegate the Optimizing Plan to the Optimizer for execution. 

For this, some prerequisite refactoring work is required.

This PR moves the code of the Optimizing Plan from the AMS module to the iceberg/mixed-format module, and the relevant logic can be called by the optimizer in the future.

## Brief change log

- Move Optimizing Plan related codes to iceberg/mixed-format module 
- Add a mixed-iceberg rewrite executor factory 

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by zhoujinsong — COMMENTED** [review]
@baiyangtx Thanks for the contribution!

It is very important to the new process API feature.

The PR look good to me in general, I left some minor suggestion, PTAL.

**Review by Aireed — APPROVED** [review]
LGTM.  
Question: After this refactoring, can Spark customize procedures to trigger optimization?  （only depend on the plan and scan logical)

**Review by zhoujinsong — APPROVED** [review]
LGTM.

**Comment by baiyangtx** [comment]
> LGTM. Question: After this refactoring, can Spark customize procedures to trigger optimization? （only depend on the plan and scan logical)

1. Committer still in `ams-module`
2. These refactorings only involve core-level code, and the engine still needs to adapt.

**Pull request merged**
