### PR TITLE
[AMORO-3309][Improvement] Support for terminal integration with LDAP authentication in Kyuubi

### PR DESCRIPTION
**Pull request by Aireed**
## Why are the changes needed?

Close #xxx.
Support for terminal integration with LDAP authentication in Kyuubi

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by baiyangtx — COMMENTED** [review]
When LDAP is enabled, how is authentication information passed to Kyuubi?

**Comment by Aireed** [comment]
> When LDAP is enabled, how is authentication information passed to Kyuubi?

image


Referring to this configuration manual, you can directly include the username and password in the URL

**Comment by tcodehuber** [comment]
@Aireed  Can you also improve the helm charts? This can make us enable this feature easily. refs: https://github.com/apache/amoro/blob/master/charts/amoro/templates/amoro-configmap.yaml

**Comment by Aireed** [comment]
> @Aireed Can you also improve the helm charts? This can make us enable this feature easily. refs: https://github.com/apache/amoro/blob/master/charts/amoro/templates/amoro-configmap.yaml https://github.com/apache/amoro/blob/master/charts/amoro/values.yaml

I have updated the commition,  PTAL. 3ks

**Review by czy006 — APPROVED** [review]
LGTM

**Comment by zhoujinsong** [comment]
Thanks for the contribution!

**Pull request merged**
