### PR TITLE
Pull module amoro-ams-server as amoro-ams directly

### LINKED ISSUE #3161: [Improvement]: Pull module amoro-ams-server as amoro-ams directly
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

As title

### How should we improve?

As title

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by majin1102**
## Why are the changes needed?

Close #3161.

## Brief change log

- Only move module location

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by zhoujinsong** [comment]
Maybe `amoro-server` is a proper name for the module now, HDYT? @majin1102

**Comment by majin1102** [comment]
> Maybe `amoro-server` is a proper name for the module now, HDYT? @majin1102

amoro-server could be fine as well as amoro-ams. ams -> amoro management server/service
If we eliminate ams concept, that would introduce a lot of paper work which is quite unnecessary. Besides, amoro-server is too common and can not be distingushed with amoro-scheduler

**Review by baiyangtx — APPROVED** [review]
LGTM

**Comment by baiyangtx** [comment]
> Maybe `amoro-server` is a proper name for the module now, HDYT? @majin1102

II also prefer `amoro-server`

**Pull request merged**
