### PR TITLE
[AMORO-3039] Update optimized snapshot id when optimizing evaluation result is unnecessary

### LINKED ISSUE #3039: [Improvement]: Stopped repeating the evaluation when there are no new snapshots on table
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

When there are no new entries being written to the table, and the conditions on the table do not meet the triggering criteria for optimizing, the table will continue to undergo meaningless optimizing evaluations.

### How should we improve?

Stopped repeating the evaluation when the optimizing condition was not matched and no new snapshot was added.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhoujinsong**
## Why are the changes needed?

Close #3039.

## Brief change log

- Update optimized snapshot id when optimizing evaluation result is unnecessary.

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by zhoujinsong** [comment]
This PR modifies the meaning of the `last optimized snapshot ID`. It no longer specifically points to the last snapshot that completed optimizing. Instead, when optimizing is not required on the table, it actually points to a snapshot ID that doesn't need optimizing. I believe this change is meaningful, as we should be more concerned about which snapshot doesn't require optimizing.

**Review by huyuanfeng2018 — APPROVED** [review]
LGTM.

**Review by XBaith — APPROVED** [review]
Good optimisation

**Review by czy006 — APPROVED** [review]
LGTM

**Pull request merged**
