### PR TITLE
chore: remove copyright.txt

### PR DESCRIPTION
**Pull request by caicancai**
## Why are the changes needed?

remove copyright.txt

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by caicancai** [comment]
@zhoujinsong I think the copyright can be deleted, what do you think?

**Comment by zhongqishang** [comment]
@caicancai  Thanks for your contribution.

`copyright.txt` is used with the spotless plugin to generate and validate the copyright of the java/scala file. 
What is the reason for remove it?

**Comment by zhongqishang** [comment]
> > @caicancai Thanks for your contribution.
> > `copyright.txt` is used with the spotless plugin to generate and validate the copyright of the java/scala file. What is the reason for remove it?
> 
> I'm not sure about this. I have the impression that many apache projects have deleted this file. According to you, we should keep it. Thank you for your reply.

This way can only include java/scala files and does not take effect for other files. I think other projects have been deleted because there is a better way to verify, like [flink license_check.sh](https://github.com/apache/flink/blob/master/tools/ci/license_check.sh), or use apache rat plugin, like kyuubi.

I think we should include all files as well.

**Comment by caicancai** [comment]
close first

**Pull request closed without merging**
