### PR TITLE
[Improvement]: Eliminate AMS Full GC impact deriving from local terminal clean spark context #2969

### LINKED ISSUE #2969: [Improvement]: Eliminate AMS Full GC impact deriving from local terminal clean spark context
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

We experienced and suffered from AMS full GC for a long period. we dig into this case and finally found out  local spark session terminal triggers java.lang.System.gc() every 30 minutes  to clean contexts. As arthas stack traces as shown below:
image

### How should we improve?

For external kyuubi session terminal, there is no need to revises anything. The problem is only related to local session which is embedding into AMS itself. Simply add  config 'spark.cleaner.referenceTracking' = 'false' to solve the problem.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by nicochen**
This pr is related to issue #2969 and has been manually tested locally.

## Why are the changes needed?

Close #2969.

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by daragu — APPROVED** [review]

**Comment by baiyangtx** [comment]
I think it might be more reasonable to adjust the value of `spark.cleaner.periodicGC.interval`

From codes of spark, the parameter `spark.cleaner.referenceTracking` controls whether to create the context cleaner.

image

And inside the ContextCleaner, there are two theads managed.

- A cleanThread, will clean RDD nolonger be used.
- A gcThread, call `System.gc` every `spark.cleaner.periodicGC.interval` period.

image
image
image

I think the role of the cleanThread is quite important, especially when we start a resident Spark Context, which can release disk resources in time.
On the other hand, GC triggered by AMS is not a big problem. The parameter `spark.cleaner.periodicGC.interval` can be adjusted to a very large value to avoid actively triggering GC.

**Comment by nicochen** [comment]
@baiyangtx I also considered the 'spark.cleaner.periodicGC.interval ' config key before, but as you said we can only set it an extremely large number rather than disabling it. In our production case, the full GC really matters. The 1.8 JDK uses parallel gc as full gc strategy for G1,.As a result, it takes more than 30 secs and triggers zk timeout and AMS failover which is unacceptable. Also, I believe the local terminal is designed to take lightweight and less frequent sql tasks and it would not produce too much RDD \ shuffle trash. The heavy tasks should go to kyubi or spark . Thus, I choose overall stability instead of enlarge number of gc interval.

**Review by zhoujinsong — APPROVED** [review]
LGTM.

**Comment by zhoujinsong** [comment]
@baiyangtx  What do you think about the PR now?

**Review by baiyangtx — APPROVED** [review]
LGTM,  Diable RDD clean does not matter for local spark session.

**Pull request merged**
