### PR TITLE
[AMORO-2782]: Improve the error message for OptimizerGroup scale-out

### LINKED ISSUE #2782: [Improvement]: Improve the error message for OptimizerGroup scale-out
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Improve the error message for configure OptimzierGroupconfiguring

For example, if configured the `memory` with `4096m`, it can saved successfully but will pop the below error when `Scale-out`
企业微信截图_6a273038-296d-464d-b8e5-381a84d12179

### How should we improve?

IMHO we can improve this:
1. add some check when the configuration save trigged
2. Give some meaningful message if there is something wrong when scale-out

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by jiamin13579**
## Why are the changes needed?

Close #2782 .
image

## Brief change log

-  Improve the error message
-  Update doc

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by tcodehuber** [comment]
@jiamin13579 Thanks for your contribution. IMO, I suggest you can add `public static long xbToByte(String size)/ org.apache.amoro.server.dashboard.utils.AmsUtil` instead of import another util class. 

Furthermore, it's better to inform end users if he/she inputed illegal value.

**Review by majin1102 — CHANGES_REQUESTED** [review]
Thanks for your contribution.

This seems a memory unit transformation in dashboard module, why not define the utility there.

I suggest transport it there and leave server clear, the parameter could be defined as memoryAsMegabytes or something

**Review by tcodehuber — APPROVED** [review]
LGTM

**Review by majin1102 — APPROVED** [review]
LGTM

**Pull request merged**
