### PR TITLE
Change project version to 0.8-SNAPSHOT

### PR DESCRIPTION
**Pull request by zhoujinsong**
## Why are the changes needed?

After we release 0.7.0, we may need to upgrade the project version.

## Brief change log

- Change the project version to 0.8-SNAPSHOT

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Review by czy006 — COMMENTED** [review]
Helm Chart Need to change 0.8-SNAPSHOT ? but we don't have this image

**Comment by zhoujinsong** [comment]
> Helm Chart Need to change 0.8-SNAPSHOT ? but we don't have this image

We can change it to the stable version:0.7.0-incubating or the snapshot version:master-snapshot.
HDYT?

**Comment by czy006** [comment]
> > Helm Chart Need to change 0.8-SNAPSHOT ? but we don't have this image
> 
> We can change it to the stable version:0.7.0-incubating or the snapshot version:master-snapshot. HDYT?

if we change **master-snapshot**, we push the lastest image everyday to dockerhub?

**Comment by zhoujinsong** [comment]
> if we change **master-snapshot**, we push the lastest image everyday to dockerhub?

The master snapshot is updated daily, regardless of whether the version in Helm is modified.

I prefer to change it to the stable version in Helm.

**Review by czy006 — APPROVED** [review]

**Review by tcodehuber — APPROVED** [review]
LGTM

**Pull request merged**
