### PR TITLE
[AMORO-2761] Use junit-bom to simplify junit dependencies

### LINKED ISSUE #2761: [Improvement]: Use junit bom dependencies
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Use junit bom to simplify dependencies.

### How should we improve?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by link3280**
## Why are the changes needed?

Close #2761.

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by link3280** [comment]
@zhoujinsong Should be a quick one. PTAL.

**Review by zhoujinsong — APPROVED** [review]
LGTM.

Thanks for the contribution! @link3280

**Review by baiyangtx — COMMENTED** [review]
Do we need to modify the dependencies in each module?

**Comment by link3280** [comment]
> Do we need to modify the dependencies in each module?

@baiyangtx The submodules would inherit the plugin management, so it will be fine.

**Pull request merged**
