### PR TITLE
[AMORO-2746] The artifactId of the sub modules of ams should use the same prefix

### LINKED ISSUE #2746: [Improvement]: The artifactId of the sub modules of ams should use the same prefix
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

The artifactId of the sub modules of ams should use the same prefix
- change `amoro-optimizer` to `amoro-ams-optimizer`
- change `amoro-metric-reporter` to `amoro-ams-metric-reporter`

### How should we improve?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xleoken**
## Why are the changes needed?

Close #2746 .

## Brief change log

The artifactId of the sub modules of ams should use the same prefix
- change `amoro-optimizer` to `amoro-ams-optimizer`
- change `amoro-metric-reporter` to `amoro-ams-metric-reporter`

image

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by zhongqishang** [comment]
Thanks for your contribution.

I think the sub module also needs to be changed, the generated jar starts with `amoro` will be best, `-ams` can be omitted.

```
prometheus-reporter -> amoro-prometheus-reporter
optimizer-common ->  amoro-optimizer-common
flink-optimizer -> amoro-flink-optimizer
spark-optimizer -> amoro-spark-optimizer
standalone-optimizer -> amoro-standalone-optimizer
```

WDYT? @xleoken @zhoujinsong

**Comment by xleoken** [comment]
hi @zhongqishang, it seems better that moving `dist`、`optimizer` module to under the root(amoro) folder

**Comment by zhongqishang** [comment]
> hi @zhongqishang, it seems better that moving `dist`、`optimizer` module to under the root(amoro) folder

`optimizer` is a part of ams, I think the current module structure is appropriate, refer to #2627 .

Of course, there is no problem with the current PR. We can discuss the optimizer/reporter jar name later.

**Review by zhongqishang — APPROVED** [review]
LGTM.

**Comment by xleoken** [comment]
> > hi @zhongqishang, it seems better that moving `dist`、`optimizer` module to under the root(amoro) folder
> 
> `optimizer` is a part of ams, I think the current module structure is appropriate, refer to #2627 .
> 
> Of course, there is no problem with the current PR. We can discuss the optimizer/reporter jar name later.

thanks

**Pull request merged**
