### PR TITLE
Change group id from `com.netease.amoro` to `org.apache.amoro`

### PR DESCRIPTION
**Pull request by zhoujinsong**
## Why are the changes needed?

Change the group id to org.apache.amoro`.

## Brief change log

- Change group id from `com.netease.amoro` to `org.apache.amoro` in poms.
- Change some descriptions in docs due to group id change.

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Review by Aireed — APPROVED** [review]

**Review by baiyangtx — COMMENTED** [review]
There are some class name in `/charts` need to be changed.

**Comment by czy006** [comment]
> There are some class name in `/charts` need to be changed.

Maybe need to subtask

**Comment by zhongqishang** [comment]
> > There are some class name in `/charts` need to be changed.
> 
> Maybe need to subtask

+1 for subtask.

This PR is only cover change group id, not include package name, I think we can resolve it in a new PR.

**Review by czy006 — APPROVED** [review]
LGTM

**Comment by zhoujinsong** [comment]
Yes, I plan to create PRs to modify the package names, submitting one PR for each module maybe.

**Pull request merged**
