### PR TITLE
[AMORO-2988] Add more base info for the table detail page

### LINKED ISSUE #2988: [Improvement]: Add more base info for the table detail page
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

As titiled

### How should we improve?

1. Add optimizing status, records, last commit time;
2. Only display `tableName` -> `database.tableName`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by tcodehuber**
## Why are the changes needed?

Close #2988.

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by tcodehuber** [comment]
image

**Comment by XBaith** [comment]
It is OK to display other dimensions of information under the title, but I have a small suggestion. The information under the current table title and the metrics column on the right are a lot of duplication. I think the information under the title can be simplified. For example, the last commit time, table size, file count, avg file size and other information can be placed on the right.

**Comment by tcodehuber** [comment]
> It is OK to display other dimensions of information under the title, but I have a small suggestion. The information under the current table title and the metrics column on the right are a lot of duplication. I think the information under the title can be simplified. For example, the last commit time, table size, file count, avg file size and other information can be placed on the right.

If the optimizing status, records and table format is remained under the current table title, is it OK or do you have any suggestion which else information can be displayed there?

**Comment by tcodehuber** [comment]
> It is OK to display other dimensions of information under the title, but I have a small suggestion. The information under the current table title and the metrics column on the right are a lot of duplication. I think the information under the title can be simplified. For example, the last commit time, table size, file count, avg file size and other information can be placed on the right.
> 
@XBaith  If the optimizing status, records and table format is remained under the current table title, is it OK or do you have any suggestion which else information can be displayed there?

**Comment by XBaith** [comment]
> @XBaith If the optimizing status, records and table format is remained under the current table title, is it OK or do you have any suggestion which else information can be displayed there?

That's ok for me. 
We can display full table identifier as title, `<catalog>.<database>.<table>`
image

**Review by zhangmo8 — APPROVED** [review]
LGTM

**Comment by XBaith** [comment]
I think some of the metrics under the table identifier that duplicate the right hand side detail metrics should be removed, WDYT?

**Comment by tcodehuber** [comment]
> I think some of the metrics under the table identifier that duplicate the right hand side detail metrics should be removed, WDYT?

frontend or backend code?

**Comment by XBaith** [comment]
> last commit time, table size, file count, avg file size

Front side, metrics: last commit time, table size, file count and avg file size can be removed from the title?

**Comment by tcodehuber** [comment]
image

**Comment by tcodehuber** [comment]
> > last commit time, table size, file count, avg file size
> 
> Front side, metrics: last commit time, table size, file count and avg file size can be removed from the title?

Updated.

**Review by XBaith — APPROVED** [review]
Thank you! It's ok for me, do you have any suggestions? @zhoujinsong

**Comment by zhoujinsong** [comment]
@tcodehuber Thanks for the contribution!

I'm wondering if `Optimizing Status` would be better. `Optimizing` highlights our continuous optimization capability, and here the `status` perfectly corresponds to the ongoing actions of continuous optimization.

**Comment by tcodehuber** [comment]
> @tcodehuber Thanks for the contribution!
> 
> I'm wondering if `Optimizing Status` would be better. `Optimizing` highlights our continuous optimization capability, and here the `status` perfectly corresponds to the ongoing actions of continuous optimization.

OK, I have followed your suggestion.

**Review by zhoujinsong — APPROVED** [review]
LGTM.

**Pull request merged**
