### PR TITLE
[WIP] [AMORO-2068] Adjust api path and controller

### PR DESCRIPTION
**Pull request by GOODBOY008**
Adjust api path and controller

### CODE REVIEW

**Comment by GOODBOY008** [comment]
@shidayang About controller adjustment can you give me some suggestion?

**Comment by zhoujinsong** [comment]
@GOODBOY008 Thanks a lot for driving this.

At present, the routing rules of the API do appear somewhat messy. We should organize them better for easier long-term management.However, before we formally begin, we may need to clarify some issues like :

- Identify APIs that have expired, such as `/docs/latest` and `/hive-tables/upgrade`, which do not appear to be relied upon by the frontend anymore.
- Clarify the differences between the `ams/v1` and `ams/v1/api` APIs, discuss whether both APIs still need to be maintained simultaneously, and better manage them in the code.

**Comment by zhoujinsong** [comment]
BTW, I strongly recommend that you follow the project template in your PR description so that other developers can better understand the content of your PR, such as related issues, brief change logs, test methods, etc.

**Comment by zhoujinsong** [comment]
After an offline discussion with @Aireed @hameizi, here are some updates regarding this issue:

- `/docs/latest` is no longer needed, but `/hive-tables/upgrade` is still needed.
- APIs starting with `/ams/v1` are used by the dashboard frontend and APIs starting with `/api/ams/v1` are used by other ecosystems. At this stage, they basically support the same interfaces and implementations, but there are differences in authentication methods.

Based on this, we can also make the following improvements:

- Remove APIs no longer needed.
- Uniform routing rules for the same interface parts of `/ams/v1` and `/api/ams/v1`.

@GOODBOY008  HDYT?

**Comment by GOODBOY008** [comment]
> After an offline discussion with @Aireed @hameizi, here are some updates regarding this issue:
> 
> * `/docs/latest` is no longer needed, but `/hive-tables/upgrade` is still needed.
> * APIs starting with `/ams/v1` are used by the dashboard frontend and APIs starting with `/api/ams/v1` are used by other ecosystems. At this stage, they basically support the same interfaces and implementations, but there are differences in authentication methods.
> 
> Based on this, we can also make the following improvements:
> 
> * Remove APIs no longer needed.
> * Uniform routing rules for the same interface parts of `/ams/v1` and `/api/ams/v1`.
> 
> @GOODBOY008 HDYT?

@zhoujinsong Yes, I will discuss detail with @shidayang and append conclusion in this pr.

**Comment by GOODBOY008** [comment]
@zhoujinsong @shidayang I remove exist api both `/ams/v1` and `/api/ams/v1` the diff as below. I think conbine it as one will be better. I wonder `tableController::getTableDetailTabToken` is useless because we already have `apikey` and `signature` check.
企业微信截图_16981484882836

**Comment by shidayang** [comment]
> @zhoujinsong @shidayang I remove exist api both `/ams/v1` and `/api/ams/v1` the diff as below. I think combine them as one will be better. I wonder `tableController::getTableDetailTabToken` is useless because we already have `apikey` and `signature` check. 企业微信截图_16981484882836

Except for /login and /login/current, all others can be merged. getTableDetailTabToken should not be necessary.

**Comment by zhoujinsong** [comment]
Closed by #3014

**Pull request closed without merging**
